version: '3.9'

services:
  db:
    image: postgres:13
    container_name: lavanderia-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lavanderia-nextjs
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build: .
    container_name: lavanderia-app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/lavanderia-nextjs
      PORT: 3000
      JWT_SECRET: laundry
      NEXT_PUBLIC_IVMS_URL_SOCKET: "http://192.168.10.87:3000"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data: