import { DepartmentSeed } from "./departments";
export const CollaboratorsSeed: {
    cpf: string;
    name: string;
    type: "registrado" | "pj" | "diarista";
    department: typeof DepartmentSeed[number];
}[] = [
{
    cpf: "11685090842",
    name: "EDUARDO CAGNOTTO",
    type:"registrado",
    department: "recepção",
},
{
    cpf: "37141638830",
    name: "DANIELLY RESAFFE",
    type:"registrado",
    department: "recepção",
},
{
    cpf: "51550582879",
    name: "MARIA JULIA BRANDÃO DE OLIVEIRA ",
    type:"registrado",
    department: "recepção",
},
{
    cpf: "08384497869",
    name: "KATIA VIEIRA PEREIRA",
    type:"registrado",
    department: "comercial",
},
{
    cpf: "36573960807",
    name: "JOABEL SOARES DE SOUZA PIRES",
    type:"pj",
    department: "comercial",

},
{
    cpf: "45546352876",
    name: "YAM RIKHER FORMICA COIMBRA RABELLO",
    type:"pj",
    department: "comercial",
},
{
    cpf: "43193377864",
    name: "ANA SARA DEL RIO",
    type:"registrado",
    department: "comercial",
},
{
    cpf: "41307774830",
    name: "VICTORIA DIAS GHELLER",
    type:"pj",
    department: "comercial",
},
{
    cpf: "50113316879",
    name: "PATRICIA CAMARGO MACIEL ",
    type:"registrado",
    department: "comercial",
},
{
    cpf: "39905444890",
    name: "LUANA CRISTINA MOREIRA ANSELMO ",
    type:"registrado",
    department: "comercial",
},
{
    cpf: "52816172813",
    name: "VITORIA ISEIS SOARES ",
    type:"pj",
    department: "comercial",
},
{
    cpf: "31483271870",
    name: "ROBERTA CONESTABILE",
    type:"registrado",
    department: "comercial",
},
{
    cpf: "22231563800",
    name: "GLACIELE ISABEL DA SILVA MIGUEL",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "29702688841",
    name: "DELANIA REGINA MOURA COSTA",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "35144086888",
    name: "JANAINA RODRIGUES",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "32384303864",
    name: "THATIANA CREVELARI",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "37146722813",
    name: "ALESSANDRA LARANJEIRA VANINI ",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "44844040871",
    name: "MATHEUS ALVES PIZARRO",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "41180083865",
    name: "LOUISIE EDUARDA JORGE DE OLIVEIRA ",
    type:"registrado",
    department: "administrativo",
},
{
    cpf: "37292894895",
    name: "ANA PAULA ALCANTARA DA SILVA",
    type:"registrado",
    department: "operacional",
},
{
    cpf: "00637586107",
    name: "ERIC DINIZ DE SOUSA ",
    type:"registrado",
    department: "operacional",
},
{
    cpf: "47805373809",
    name: "VITORIA DE PAULA CRUZ ",
    type:"registrado",
    department: "operacional",
},
{
    cpf: "45533220801",
    name: "BRUNA LETICIA DE ALMEIDA ",
    type:"registrado",
    department: "operacional",
},
{
    cpf: "18463689876",
    name: "VIVIANE MIRANDA DE MORAES MANSO",
    type:"registrado",
    department: "financeiro",
},
{
    cpf: "14346055826",
    name: "ANA PAULA PEDACE",
    type:"registrado",
    department: "comercial",
},
{
    cpf: "06642582802",
    name: "URBANO ROMPATO",
    type:"registrado",
    department: "motorista",
},
{
    cpf: "41285558863",
    name: "HELLEN JOYCE LOPES SILVA",
    type:"registrado",
    department: "beach tennis",
},
{
    cpf: "36736341515",
    name: "ERIVALDO DOS SANTOS (WAL)",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "12861930870",
    name: "ALAIDE DOS SANTOS RIBAS COELHO",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "25237439810",
    name: "MARIA VILANI DA SILVA BEZERRA",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "79437346291",
    name: "ADERLEY ALEX GOMES MOTA",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "36167968810",
    name: "ELIGIA PEREIRA",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "09161839809",
    name: "MARCELO SOUZA SILVEIRA",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "44343211886",
    name: "LUIZ GUSTAVO DE FRANCISCO FILHO",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "07197534577",
    name: "ALINE DOS SANTOS",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "71672966191",
    name: "MARIA BARBARA FERREIRA DA SILVA",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "21658015835",
    name: "SAMUEL RODRIGUES CORREA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "44623872874",
    name: "KAYLA HERMIONE CAGNOTTO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "58098543897",
    name: "GIOVANA CEZAR BRONZATI ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "42234569893",
    name: "CARLOS EDUARDO ANDRADE MACEDO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "14954916410",
    name: "MAIARA MORAIS CAVALCANTE DE BARROS ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "35897855862",
    name: "JONATAS NUNES DOS SANTOS ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "44087522822",
    name: "MARIZA CRISTINA DOS SANTOS ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "51851581820",
    name: "BIANCA BEATRIZ BARBOSA NABARRO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "54529351858",
    name: "VITORIA THAIS PERES DE OLIVEIRA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "48193525809",
    name: "NATALIA SANTOS SILVA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "38350263806",
    name: "KHEVELY LIMA OLIVEIRA",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "53220557899",
    name: "LUCAS HENRIQUE RODRIGUES NASCIMENTO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "34622182807",
    name: "VANESSA MELO DO NASCIMENTO AMORIM",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "60983816310",
    name: "MARIA LUIZA DA SILVA OLIVEIRA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "17476395832",
    name: "ELOISA DE SOUZA SILVA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "03601090805",
    name: "DANIEL SABINO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "11618255509",
    name: "BRUNO BARROS DOS SANTOS ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "35051969836",
    name: "LUIZ FELIPE DE FRANCISCO",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "51533212821",
    name: "PATRICIA MARIA DE SANTANA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "45881129881",
    name: "MATHEUS FIGUEIREDO RIVELLES ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "50394294874",
    name: "BRUNA MARQUES SABINO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "53807971807",
    name: "JHONATAN PEREIRA GONÇALVES ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "semcpf001",
    name: "DIA-GENILDA CASTRO DOS SANTOS ",
    type:"diarista",
    department: "cozinha e cantina",

},
{
    cpf: "38898895810",
    name: "FABIANA DOS SANTOS PEREIRA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "29147773880",
    name: "SUELI DA SILVA CORDEIRO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "41902476859",
    name: "OTAVIO LUIZ FRIGERI ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "42890571874",
    name: "MARINA BARRETO CORREA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "semcpf002",
    name: "DIA-PATRICIA MARIA DE JESUS SANTOS ",
    type:"diarista",
    department: "cozinha e cantina",

},
{
    cpf: "35349225812",
    name: "WELINGTON SANTOS DE CARVALHO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "09964834110",
    name: "GABRIELA VITOR TRENTIN ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "45408974898",
    name: "LUCAS DIRCEU DOS SANTOS",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "35595224800",
    name: "DIA-DJALMA FURTADO",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "09742172552",
    name: "JEDERSON OLIVEIRA CRUZ SAMPAIO ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "51486468888",
    name: "MARLON DA SILVA E SILVA ",
    type:"registrado",
    department: "cozinha e cantina",
},
{
    cpf: "25650765847",
    name: "PATRICIA APARECIDA LOPES",
    type:"registrado",
    department: "lavanderia",
},
{
    cpf: "09762796810",
    name: "MARIA SALETE RIBEIRO BRITO",
    type:"registrado",
    department: "lavanderia",
},
{
    cpf: "18576350866",
    name: "ROSA DE FÁTIMA GODÓI",
    type:"registrado",
    department: "lavanderia",
},
{
    cpf: "35466339890",
    name: "PRISCILA SALLA",
    type:"registrado",
    department: "lavanderia",
},
{
    cpf: "03979203506",
    name: "SILVANIA DOS SANTOS M ALVES",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "14991843871",
    name: "APARECIDA FREIRE DE ANDRADE",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "33918510824",
    name: "PATRICIA APARECIDA COLAÇO MOREIRA",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "08623560400",
    name: "ORDELANDIA DE ALMEIDA ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "35533348867",
    name: "PATRICIA SALLA",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "44676422857",
    name: "MAYCON ALEX BARBOSA ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "43577327863",
    name: "RENATA ALVES ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "08488468504",
    name: "SABRIELA SODRE DE JESUS ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "40849278805",
    name: "NAFALY TAIRINY OLIVEIRA DE SANTANA ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "37047805885",
    name: "ROSA MARIA CAMILO ALVES ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "57917910890",
    name: "ANA CAROLINA DE OLIVEIRA DOS SANTOS ",
    type:"registrado",
    department: "govarnança",
},
{
    cpf: "11309323895",
    name: "BENEDITO APARECIDO DONIZETI BUENO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "06493087511",
    name: "ELISEU CALDAS DA SILVA ",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "29227012800",
    name: "ADRIANA RIBEIRO ",
    type:"registrado",
    department: "costura",
},
{
    cpf: "22010199839",
    name: "JANI ROBERTA AFONSO ",
    type:"registrado",
    department: "costura",
},
{
    cpf: "44093952892",
    name: "ALEX COSTA SOUZA",
    type:"registrado",
    department: "piscina",
},
{
    cpf: "42134586877",
    name: "LUCAS OLIVEIRA DOS SANTOS ",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "17221497877",
    name: "VALDEIR APARECIDO DE BARROS",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "57788111520",
    name: "EDIMAR CHRIST SANTANA",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "05865078500",
    name: "JOSÉ RIBEIRO DOS SANTOS ",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "45684633862",
    name: "LUIZ GABRIEL DALONSO ",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "45466581844",
    name: "LUCAS MIQUELINO ",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "30308768884",
    name: "EDSON MAURICIO ROLHA ",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "00003084124",
    name: "EDSON DE SOUZA RODRIGUES ",
    type:"registrado",
    department: "jardim",
},
{
    cpf: "33196421899",
    name: "JEAN FELIPE AMANCIO GONZALES RODRIGUES ",
    type:"registrado",
    department: "monitoria",
},
{
    cpf: "41547003839",
    name: "DIANA THEODORO LOPES ",
    type:"registrado",
    department: "enfermaria",
},
{
    cpf: "12008686841",
    name: "MARTA DE OLIVEIRA ",
    type:"registrado",
    department: "enfermaria",
},
{
    cpf: "28298469828",
    name: "JOSE SERGIO MARCELINO DE QUEIROZ",
    type:"registrado",
    department: "portaria",
},
{
    cpf: "19534394890",
    name: "LUIS CARLOS DOS SANTOS",
    type:"registrado",
    department: "portaria",
},
{
    cpf: "07702321830",
    name: "EGIDIO WALDIR DERENGOSKI",
    type:"registrado",
    department: "portaria",
},
{
    cpf: "31877058807",
    name: "JOSÉ ANTONIO SCARANELO",
    type:"registrado",
    department: "portaria",
},
{
    cpf: "27421901809",
    name: "REGINALDO APARECIDO DO PRADO ",
    type:"registrado",
    department: "portaria",
},
{
    cpf: "31312242825",
    name: "GUILHERME BUENO ",
    type:"registrado",
    department: "portaria",
},
{
    cpf: "08536086874",
    name: "ANTONIO NILSON FURLANETTO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "42862826863",
    name: "MAICK ARIEL SMANIOTTO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "22503663818",
    name: "OSVALDO JOAO PESSOA",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "05053057800",
    name: "DOMINGOS REINALDO CRIVELARI",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "13104738890",
    name: "JOSE MARIA MORASSUTI",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "27990021889",
    name: "LEONARDO MACHADO BUENO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "13332178890",
    name: "SEBASTIÃO PEDRO DO NASCIMENTO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "18390330881",
    name: "ANDRE LUIZ DE CARVALHO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "80725597453",
    name: "FRANCISCO BATISTA DE AZEVEDO ",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "35974910818",
    name: "ROGERIO LIMONI CABRALINO ",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "26210276873",
    name: "MOISES CARLOS DE OLIVEIRA ",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "semcpf003",
    name: "WILIAN RAFAEL MORAES",
    type:"diarista",
    department: "manutenção",

},
{
    cpf: "46585380835",
    name: "ANDREY NICOLLAS AMANCIO DA SILVA ",
    type:"registrado",
    department: "tecnica",
},
{
    cpf: "55093366846",
    name: "BEATRIZ GUERREIRO VITAL COSTA ",
    type:"registrado",
    department: "tecnica",
},
{
    cpf: "semcpf004",
    name: "PATRICK RABELLO",
    type:"diarista",
    department: "informatica",

},
{
    cpf: "43733781856",
    name: "BRUNO FURLANETTO",
    type:"pj",
    department: "informatica",
},
{
    cpf: "18361666800",
    name: "ROBSON AMARO DA SILVA ",
    type:"registrado",
    department: "informatica",
},
{
    cpf: "48011162802",
    name: "MATHEUS HENRIQUE DE OLIVEIRA VIANA",
    type:"registrado",
    department: "informatica",
},
{
    cpf: "35041741883",
    name: "LEONARDO ARAUJO ROSA",
    type:"pj",
    department: "marketing",
},
{
    cpf: "semcpf005",
    name: "YASMIN EDI FORMICA RABELLO",
    type:"diarista",
    department: "marketing",

},
{
    cpf: "semcpf006",
    name: "Rafaela ",
    type:"pj",
    department: "monitoria",
},
{
    cpf: "29228741848",
    name: "ANTONIO MARCOS RICARDO ",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "19572516892",
    name: "ANTONIO MARCOS DA SILVA ",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "semcpf007",
    name: "JOSY TORRICELI DE SOUSA",
    type:"diarista",
    department: "fazenda",

},
{
    cpf: "11689755814",
    name: "AUGUSTO LOPES DA SILVA",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "20639559808",
    name: "ADILSON TEIXEIRA DE ANDRADE",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "07454288863",
    name: "LUIS MARCIO MACARI",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "32674157801",
    name: "RODRIGO DE OLIVEIRA",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "07946555806",
    name: "ROBERTO ANTONIO ",
    type:"registrado",
    department: "fazenda",
},
{
    cpf: "15982299820",
    name: "RONALDO GARCIA",
    type:"pj",
    department: "CEU",
},
{
    cpf: "42449142851",
    name: "MON-KAROLINE ADORNO DUTRA",
    type:"pj",
    department: "CEU",
},
{
    cpf: "44284057820",
    name: "RAFAEL PEREIRA MARQUES",
    type:"pj",
    department: "CEU",
},
{
    cpf: "15613633835",
    name: "ANDRE FONSECA DA SILVA",
    type:"pj",
    department: "desenvolvimento",
},
{
    cpf: "36456069807",
    name: "GABRIEL FERNANDO MELO DE SOUZA",
    type:"registrado",
    department: "desenvolvimento",
},
{
    cpf: "03409123830",
    name: "MARIA ARRUDA DE OLIVEIRA",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "47120285807",
    name: "RICARDO DA SILVA BUENO",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "57197586828",
    name: "LUAN FERNANDES ALVES",
    type:"registrado",
    department: "manutenção",
},
{
    cpf: "36875545896",
    name: "TAMIRES ZANETTE DA CONCEIÇÃO ",
    type:"registrado",
    department: "beach tennis",
},
{
    cpf: "semcpf008",
    name: "DIEGO PORTA DIAS",
    type:"diarista",
    department: "beach tennis",

},
{
    cpf: "semcpf009",
    name: "WELIQUIS CHAVES DE OLIVEIRA",
    type:"diarista",
    department: "beach tennis",

},
{
    cpf: "40321805801",
    name: "LEONARDO DE LIMA SAQUI",
    type:"registrado",
    department: "beach tennis",
},
]