export const DepartmentSeed = [
"recepção",
"comercial",
"administrativo",
"operacional",
"financeiro",
"motorista",
"beach tennis",
"cozinha e cantina",
"jardim",
"lavanderia",
"governança",
"manutenção",
"costura",
"piscina",
"monitoria",
"enfermaria",
"portaria",
"tecnica",
"informatica",
"marketing",
"fazenda",
"CEU",
"desenvolvimento",
] as const