export const ProductsSeed = [
    {
        product: 'Camiseta Amarela',
        type: 'Camiseta',
        service: 'Brotas Eco',
        size: 'P',
        unitary_value: 20.00,
        barcode: '00000005',
        toSector: true,
    },
    {
        product: 'Camiseta Amarela',
        type: 'Camiseta',
        service: 'Brotas Eco',
        size: 'M',
        unitary_value: 20.00,
        barcode: '00000004',
        toSector: true,
    },
    {
        product: 'Camiseta Amarela',
        type: 'Camiseta',
        service: 'Brotas Eco',
        size: 'G',
        unitary_value: 20.00,
        barcode: '00000003',
        toSector: true,
    },
    {
        product: 'Camiseta Amarela',
        type: 'Camiseta',
        service: 'Brotas Eco',
        size: 'GG',
        unitary_value: 20.00,
        barcode: '00000002',
        toSector: true,
    },
    {
        product: 'Bermuda Monitoria preta',
        type: 'Bermuda',
        service: 'Peraltas',
        size: 'P',
        unitary_value: 20.00,
        barcode: '00000001',
        toSector: true,
    },
    {
        product: 'Bermuda Monitoria preta',
        type: 'Bermuda',
        service: 'Peraltas',
        size: 'M',
        unitary_value: 20.00,
        toSector: true,

    },
    {
        product: 'Bermuda Monitoria preta',
        type: 'Bermuda',
        service: 'Peraltas',
        size: 'G',
        unitary_value: 20.00,
        toSector: true,
    },
    {
        product: 'Bermuda Monitoria Azul',
        type: 'Bermuda',
        service: 'Ceu',
        size: 'M',
        unitary_value: 20.00,
        toSector: true,
    },
];